Repository wp-erp/wp-erp, pull requests merged in 2020-11, with the labels that each got.

#1132 Fixed name and city validation issues
  includes/functions-people.php
  includes/functions.php
  modules/hrm/includes/class-employee.php
Labels: Needs Dev Review

#1123 Product duplicate Issue
  assets/js/i18n.js
  assets/js/vendor.js
  modules/accounting/api/class-rest-api-products.php
  modules/accounting/assets/js/admin.js
  modules/accounting/assets/js/bootstrap.js
  modules/accounting/assets/js/frontend.js
  modules/accounting/assets/js/style.js
  modules/accounting/assets/src/admin/components/products/ProductModal.vue
  modules/accounting/includes/functions/products.php
Labels: Ready to Merge

#1116 Update expense, purchase and github issues
  assets/js/vendor.js
  includes/class-updates.php
  includes/updates/update-1.6.8.php
  modules/accounting/api/class-rest-api-bills.php
  modules/accounting/api/class-rest-api-expenses.php
  modules/accounting/api/class-rest-api-pay-bills.php
  modules/accounting/api/class-rest-api-pay-purchases.php
  modules/accounting/api/class-rest-api-purchases.php
  modules/accounting/api/class-rest-api-transactions.php
  modules/accounting/assets/css/admin.css
  modules/accounting/assets/css/admin.css.map
  modules/accounting/assets/js/admin.js
  modules/accounting/assets/js/bootstrap.js
  modules/accounting/assets/js/style.js
  modules/accounting/assets/src/admin/App.vue
  modules/accounting/assets/src/admin/components/bill/BillSingle.vue
  modules/accounting/assets/src/admin/components/expense/ExpenseCreate.vue
  modules/accounting/assets/src/admin/components/expense/ExpenseSingle.vue
  modules/accounting/assets/src/admin/components/pay-bill/PayBillCreate.vue
  modules/accounting/assets/src/admin/components/pay-bill/PayBillSingle.vue
  modules/accounting/assets/src/admin/components/pay-purchase/PayPurchaseCreate.vue
  modules/accounting/assets/src/admin/components/pay-purchase/PayPurchaseSingle.vue
  modules/accounting/assets/src/admin/components/people/PeopleTransaction.vue
  modules/accounting/assets/src/admin/components/products/ProductModal.vue
  modules/accounting/assets/src/admin/components/purchase/PurchaseSingle.vue
  modules/accounting/assets/src/admin/components/select/SimpleSelect.vue
  modules/accounting/assets/src/admin/components/tax/RecordPayTax.vue
  modules/accounting/assets/src/admin/components/transactions/TransactionsFilter.vue
  modules/accounting/assets/src/admin/components/transactions/expenses/Expenses.vue
  modules/accounting/assets/src/admin/components/transactions/expenses/ExpensesList.vue
  modules/accounting/assets/src/admin/components/transactions/expenses/ExpensesStats.vue
  modules/accounting/assets/src/admin/components/transactions/purchases/Purchases.vue
  modules/accounting/assets/src/admin/components/transactions/purchases/PurchasesList.vue
  modules/accounting/assets/src/admin/components/transactions/purchases/PurchasesStats.vue
  modules/accounting/assets/src/admin/components/transactions/sales/Sales.vue
  modules/accounting/assets/src/admin/components/transactions/sales/SalesList.vue
  modules/accounting/assets/src/admin/components/transactions/sales/SalesStats.vue
  modules/accounting/includes/classes/Common.php
  modules/accounting/includes/classes/FinalAccountsHelper.php
  modules/accounting/includes/functions/bills.php
  modules/accounting/includes/functions/common.php
  modules/accounting/includes/functions/expenses.php
  modules/accounting/includes/functions/invoices.php
  modules/accounting/includes/functions/pay-bills.php
  modules/accounting/includes/functions/pay-purchases.php
  modules/accounting/includes/functions/people.php
  modules/accounting/includes/functions/product-cats.php
  modules/accounting/includes/functions/purchases.php
  modules/accounting/includes/functions/rec-payments.php
  modules/accounting/includes/functions/transactions.php
Labels: Dev Review Done, Ready to Merge

#1145 Updated delete employee to delete all leave refers
  modules/hrm/includes/functions-employee.php
Labels: Dev Review Done, Needs Testing

#1146 Show global date format
  assets/js/vendor.js
  includes/framework/views/status-report.php
  includes/functions.php
  modules/accounting/assets/js/admin.js
  modules/accounting/assets/js/bootstrap.js
  modules/accounting/assets/js/style.js
  modules/accounting/assets/src/admin/components/bill/BillSingle.vue
  modules/accounting/assets/src/admin/components/check/CheckSingle.vue
  modules/accounting/assets/src/admin/components/expense/ExpenseSingle.vue
  modules/accounting/assets/src/admin/components/journal/JournalList.vue
  modules/accounting/assets/src/admin/components/journal/JournalSingle.vue
  modules/accounting/assets/src/admin/components/pay-bill/PayBillSingle.vue
  modules/accounting/assets/src/admin/components/pay-purchase/PayPurchaseSingle.vue
  modules/accounting/assets/src/admin/components/people/PeopleDetails.vue
  modules/accounting/assets/src/admin/components/purchase/PurchaseSingle.vue
  modules/accounting/assets/src/admin/components/reports/LedgerReport.vue
  modules/accounting/assets/src/admin/components/reports/SalesTax.vue
  modules/accounting/assets/src/admin/components/tax/PayTaxSingle.vue
  modules/accounting/assets/src/admin/components/transactions/expenses/ExpensesList.vue
  modules/accounting/assets/src/admin/components/transactions/purchases/PurchasesList.vue
  modules/accounting/assets/src/admin/components/transactions/sales/InvoiceSingleContent.vue
  modules/accounting/assets/src/admin/components/transactions/sales/PaymentSingleContent.vue
  modules/accounting/assets/src/admin/components/transactions/sales/SalesList.vue
  modules/accounting/assets/src/admin/components/transfers/SingleTransfer.vue
  modules/accounting/assets/src/admin/mixins/common.js
  modules/accounting/includes/classes/class-assets.php
  modules/hrm/includes/class-employee-list-table.php
  modules/hrm/views/reporting/headcount.php
  modules/hrm/views/reporting/salary-history.php
Labels: Needs Dev Review, Needs Testing

#1142 Fix/single contact permission
  modules/crm/views/company/single.php
  modules/crm/views/contact/single.php
Labels: Dev Review Done, QA Approved, Ready to Merge

#1141 Export import vendors
  includes/admin/views/tools.php
  includes/admin/views/tools/import.php
  includes/class-validate-data.php
  includes/functions.php
Labels: Dev Review Done, Needs Testing, QA Approved, Ready to Merge
