Repository wp-erp/wp-erp, pull requests merged in 2020-12, with the labels that each got.

#1164 Added weMail section in install wizard
  includes/admin/class-setup-wizard.php
Labels: Dev Review Done, Needs Testing

#1178 Employee sync attendance
  modules/hrm/includes/class-employee.php
  modules/hrm/includes/functions-employee.php
Labels: Needs Dev Review, Needs Testing, QA Approved, Ready to Merge

#1166 Fixed employee search problem in other languages #1128
  modules/hrm/includes/class-employee-list-table.php
Labels: Needs Dev Review, Needs Testing, QA Approved, Ready to Merge

#1188 Updated employee status update action hook
  modules/hrm/includes/class-employee.php
Labels: Needs Dev Review, Needs Testing, QA Approved

#1191 Updated calender lib version
  assets/vendor/fullcalendar/fullcalendar.js
  assets/vendor/fullcalendar/fullcalendar.min.js
Labels: Needs Testing, QA Approved
