Repository wp-erp/wp-erp, pull requests merged in 2021-04, with the labels that each got.

#1227 Fix - Schedule Default auto selected and insert in the calendar by ch…
  modules/crm/views/js-templates/customer-add-schedules.php
  modules/crm/views/schedules.php
Labels: Dev Review Done, QA Approved, Ready to Merge

#1228 fix - Custom Field Add/Update Issue on save employee
  modules/hrm/includes/class-employee.php
  modules/hrm/includes/class-hr-log.php
Labels: Dev Review Done, QA Approved, Ready to Merge

#1226 Fix #1193 - Transaction filter count quantity fixed based on status, …
  assets/js/erp.js
  modules/accounting/api/class-rest-api-transactions.php
  modules/accounting/assets/src/admin/components/base/Datepicker.vue
  modules/accounting/assets/src/admin/components/transactions/TransactionsFilter.vue
  modules/accounting/assets/src/admin/components/transactions/expenses/ExpensesList.vue
  modules/accounting/assets/src/admin/components/transactions/purchases/PurchasesList.vue
  modules/accounting/assets/src/admin/components/transactions/sales/SalesList.vue
  modules/accounting/includes/functions/transactions.php
  modules/crm/assets/js/vue-table.js
  modules/crm/views/contact.php
  modules/hrm/assets/js/hrm.js
  modules/hrm/includes/class-employee-list-table.php
  modules/hrm/views/employee.php
Labels: Dev Review Done, QA Approved, Ready to Merge

#1230 fix #1147 - Remove auto complete on select date
  modules/crm/views/company/feeds.php
  modules/crm/views/contact/feeds.php
Labels: Dev Review Done, QA Approved, Ready to Merge

#1238 Added attachment feature for all section on CRM contacts
  assets/less/admin/crm.less
  modules/crm/assets/css/email-attachment.css
  modules/crm/assets/js/crm-app.js
  modules/crm/assets/js/crm-components.js
  modules/crm/includes/class-ajax.php
  modules/crm/includes/functions-customer.php
  modules/crm/views/js-templates/customer-email-note.php
  modules/crm/views/js-templates/customer-log-activity.php
  modules/crm/views/js-templates/customer-newnote.php
  modules/crm/views/js-templates/customer-schedule-note.php
  modules/crm/views/js-templates/customer-tasks-note.php
  modules/crm/views/js-templates/timeline-email.php
  modules/crm/views/js-templates/timeline-log-activity.php
  modules/crm/views/js-templates/timeline-new-note.php
  modules/crm/views/js-templates/timeline-task.php
Labels: Dev Review Done, Needs Testing, QA Approved

#1239 Fixed CRM Filter
  modules/crm/assets/js/vue-table.js
  modules/crm/views/company.php
Labels: Needs Dev Review, Needs Testing, QA Approved
