Repository wp-erp/wp-erp, pull requests merged in 2021-11, with the labels that each got.

#1310 Added translation support in growth report
  includes/functions.php
  modules/crm/views/reports/growth-report.php
Labels: QA Approved

#1309 Added offer notice for black friday
  includes/class-promotion.php
Labels: QA Approved

#1308 Fix/contact group subscriber bulk delete not working
  modules/crm/includes/class-form-handler.php
  modules/crm/views/contact-group/subscribe-contact.php
Labels: Needs Dev Review, QA Approved

#1306 Fix/responsive issue in acc tables and invoice page
  assets/less/admin/responsive.less
  modules/accounting/assets/src/admin/components/bill/BillCreate.vue
  modules/accounting/assets/src/admin/components/bill/BillSingle.vue
  modules/accounting/assets/src/admin/components/chart-accounts/ChartOfAccounts.vue
  modules/accounting/assets/src/admin/components/check/CheckCreate.vue
  modules/accounting/assets/src/admin/components/check/CheckSingle.vue
  modules/accounting/assets/src/admin/components/expense/ExpenseCreate.vue
  modules/accounting/assets/src/admin/components/expense/ExpenseSingle.vue
  modules/accounting/assets/src/admin/components/invoice/InvoiceCreate.vue
  modules/accounting/assets/src/admin/components/journal/JournalCreate.vue
  modules/accounting/assets/src/admin/components/journal/JournalSingle.vue
  modules/accounting/assets/src/admin/components/list-table/ListTable.vue
  modules/accounting/assets/src/admin/components/pay-bill/PayBillCreate.vue
  modules/accounting/assets/src/admin/components/pay-bill/PayBillSingle.vue
  modules/accounting/assets/src/admin/components/pay-purchase/PayPurchaseCreate.vue
  modules/accounting/assets/src/admin/components/pay-purchase/PayPurchaseSingle.vue
  modules/accounting/assets/src/admin/components/people/Employees.vue
  modules/accounting/assets/src/admin/components/people/People.vue
  modules/accounting/assets/src/admin/components/people/PeopleTransaction.vue
  modules/accounting/assets/src/admin/components/product-category/ProductCategory.vue
  modules/accounting/assets/src/admin/components/products/Products.vue
  modules/accounting/assets/src/admin/components/purchase/PurchaseCreate.vue
  modules/accounting/assets/src/admin/components/purchase/PurchaseSingle.vue
  modules/accounting/assets/src/admin/components/rec-payment/RecPaymentCreate.vue
  modules/accounting/assets/src/admin/components/reports/BalanceSheet.vue
  modules/accounting/assets/src/admin/components/reports/IncomeStatement.vue
  modules/accounting/assets/src/admin/components/reports/LedgerReport.vue
  modules/accounting/assets/src/admin/components/reports/TrialBalance.vue
  modules/accounting/assets/src/admin/components/reports/sales-tax/AgencyBased.vue
  modules/accounting/assets/src/admin/components/reports/sales-tax/CategoryBased.vue
  modules/accounting/assets/src/admin/components/reports/sales-tax/CustomerBased.vue
  modules/accounting/assets/src/admin/components/reports/sales-tax/TransactionBased.vue
  modules/accounting/assets/src/admin/components/tax/PayTaxSingle.vue
  modules/accounting/assets/src/admin/components/tax/SingleTaxRate.vue
  modules/accounting/assets/src/admin/components/tax/TaxAgencies.vue
  modules/accounting/assets/src/admin/components/tax/TaxCategories.vue
  modules/accounting/assets/src/admin/components/tax/TaxRates.vue
  modules/accounting/assets/src/admin/components/tax/TaxRecords.vue
  modules/accounting/assets/src/admin/components/tax/TaxZones.vue
  modules/accounting/assets/src/admin/components/transactions/expenses/ExpensesList.vue
  modules/accounting/assets/src/admin/components/transactions/purchases/PurchasesList.vue
  modules/accounting/assets/src/admin/components/transactions/sales/InvoiceSingleContent.vue
  modules/accounting/assets/src/admin/components/transactions/sales/SalesList.vue
  modules/accounting/assets/src/admin/components/transfers/NewTransfer.vue
  modules/accounting/assets/src/admin/components/transfers/Transfers.vue
Labels: QA Approved, Dev Review Done

#1305 Enhancement: Invoice Attachment Download Links in Print Mode or Invoice Link
  assets/css/invoice-front.css
  includes/class-updates.php
  includes/updates/update-1.10.2.php
  modules/accounting/assets/src/admin/components/transactions/sales/InvoiceSingleContent.vue
  modules/accounting/includes/views/transactions/invoice-readonly.php
Labels: Needs Dev Review, QA Approved

#1307 Enhance/auto entitle leave on employee type change
  modules/hrm/includes/class-employee.php
  modules/hrm/includes/class-entitlements-list-table.php
  modules/hrm/includes/class-settings.php
  modules/hrm/includes/functions-leave.php
Labels: QA Approved
