Repository wp-erp/wp-erp, pull requests merged in 2021-12, with the labels that each got.

#1316 Fixed double entry of people in accounting on auto import
  includes/functions-people.php
  modules/accounting/includes/functions/common.php
  modules/crm/assets/js/crm-contacts.js
  modules/crm/crm.php
  modules/crm/includes/class-ajax.php
  modules/crm/includes/functions-customer.php
Labels: QA Approved, Dev Review Done

#1317 replaced `&nbsp;` with space for input to the erp-pdf-invoice
  modules/accounting/includes/functions/transactions.php
Labels: QA Approved, Dev Review Done

#1314 fixed wrong module name passed to action hook 'erp_module_after_deactivated'
  includes/framework/modules.php
Labels: QA Approved, Dev Review Done

#1313 hidden Email Templates in Settings when CRM module is not active
  includes/Settings/Email.php
  modules/crm/crm.php
Labels: QA Approved, Dev Review Done

#1304 Enhance/separate crm agent contact caching
  includes/admin/class-ajax.php
  includes/functions-cache-helper.php
  includes/functions-people.php
  includes/functions.php
  modules/crm/includes/functions-customer.php
Labels: dependencies, Needs Testing, Dev Review Done

#1321 Updated PDF Invoice generator
  modules/accounting/includes/functions/transactions.php
Labels: QA Approved
