Repository wp-erp/wp-erp, pull requests merged in 2022-06, with the labels that each got.

#1337 Fix: ERP reset issues
  includes/class-scripts.php
  includes/functions.php
Labels: Needs Dev Review, QA Approved

#1333 Fix: IMAP issues
  includes/Settings/Ajax.php
  includes/Settings/Email.php
  includes/class-updates.php
  modules/crm/includes/actions-filters.php
  modules/crm/includes/admin/class-settings.php
  modules/crm/includes/functions-customer.php
Labels: QA Approved

#1323 fixed contact life-stage 2nd row not clickable on contact listing and company listing page
  modules/crm/assets/js/vue-table.js
Labels: QA Approved, Dev Review Done

#1324 fixed empty value field problem if multiple gravity-form field map to same contact field
  modules/crm/includes/contact-forms/class-contact-forms-integration.php
Labels: Dependency with Pro, QA Approved, Dev Review Done

#1327 fix/checked if CRM module is active inside `erp_get_peoples` function
  includes/functions-people.php
Labels: QA Approved, Dev Review Done

#1328 Fix/transactions filter not loading all people customer vendor
  modules/accounting/assets/src/admin/components/transactions/expenses/Expenses.vue
  modules/accounting/assets/src/admin/components/transactions/purchases/Purchases.vue
  modules/accounting/assets/src/admin/components/transactions/sales/Sales.vue
Labels: QA Approved, Dev Review Done

#1329 Fix/acc customer vendor csv sample download not working
  modules/accounting/assets/src/admin/components/people/ImportModal.vue
Labels: QA Approved, Dev Review Done

#1322 Fix/crm contact schedule different timezone issue
  modules/crm/assets/js/crm-app.js
  modules/crm/includes/functions-customer.php
  modules/crm/includes/models/activity.php
  modules/crm/views/js-templates/customer-schedule-note.php
Labels: Dependency with Pro, QA Approved, Dev Review Done

#1332 Feature/mailchimp autosync
  includes/Settings/assets/src/components/integration/Integration.vue
  includes/Settings/assets/src/mixins/common.js
  includes/Settings/assets/src/router/index.js
  includes/functions-people.php
  modules/accounting/includes/functions/purchases.php
  modules/crm/includes/class-ajax.php
  modules/crm/includes/class-subscription.php
  modules/crm/includes/functions-customer.php
Labels: Dependency with Pro, QA Approved, Dev Review Done

#1334 fix/crm-lifestage-non-english-char-problem
  modules/crm/includes/class-ajax.php
  modules/crm/views/contact/single.php
Labels: Dependency with Pro, QA Approved, Dev Review Done

#1336 Updated npm packages for compatibility
  includes/Settings/assets/src/components/base/Dropdown.vue
  modules/accounting/assets/src/admin/components/base/Dropdown.vue
  package-lock.json
  package.json
Labels: QA Approved
